### A CI workflow template that runs linting and python testing

name: Test tap-clickhouse

on: [push]

jobs:
  pytest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Start test ClickHouse
      run: docker-compose -f ".ci/docker-compose.yml" up -d --build
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Stop test ClickHouse
      if: always()
      run: docker-compose -f ".ci/docker-compose.yml" down
