### A CI workflow template that runs linting and python testing

name: Test tap-clickhouse

on: [push]

jobs:
  pytest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      postgres:
        image: clickhouse/clickhouse-server:22.5.1.2079
        env:
          CLICKHOUSE_USER: test_user
          CLICKHOUSE_PASSWORD: default
          CLICKHOUSE_DB: default
        ports:
          - "8123:8123"
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
